# Generated by Django 5.2.1 on 2025-06-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique SEO-friendly URL generated from the title', max_length=200, null=True, unique=True),
        ),
    ]
