# Generated by Django 5.2.1 on 2025-06-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_populate_slugs_in_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Unique SEO-friendly URL generated from the title', max_length=200, unique=True),
        ),
    ]
